In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/amex-dataset/test_data.parquet
/kaggle/input/amex-dataset/add_event.parquet
/kaggle/input/amex-dataset/add_trans (1).parquet
/kaggle/input/amex-dataset/offer_metadata.parquet
/kaggle/input/amex-dataset/train_data.parquet
/kaggle/input/amex-d/add_trans.parquet

In [2]:
import pandas as pd

# Path to your parquet file
parquet_file = "/kaggle/input/amex-dataset/train_data.parquet"  # Update with your file name if needed
csv_file = "train_data.csv"          # Output CSV file name

# Load the parquet file
df = pd.read_parquet(parquet_file)

# Save it as CSV
df.to_csv(csv_file, index=False)

print(f"✅ Successfully converted '{parquet_file}' to '{csv_file}'")

✅ Successfully converted '/kaggle/input/amex-dataset/train_data.parquet' to 'train_data.csv'

In [3]:
import pandas as pd

# Path to your parquet file
parquet_file = "/kaggle/input/amex-d/add_trans.parquet"  # Update with your file name if needed
csv_file = "transacrtion_data.csv"          # Output CSV file name

# Load the parquet file
df = pd.read_parquet(parquet_file)

# Save it as CSV
df.to_csv(csv_file, index=False)

print(f"✅ Successfully converted '{parquet_file}' to '{csv_file}'")

✅ Successfully converted '/kaggle/input/amex-d/add_trans.parquet' to 'transacrtion_data.csv'

In [4]:
import pandas as pd

# Load the CSV
csv_path = "/kaggle/working/train_data.csv"
df = pd.read_csv(csv_path)

# Show shape and column names
print(f"Shape of dataset: {df.shape}\n")
print("Columns:")
print(df.columns.tolist())

# Preview first few rows
df.head()

Shape of dataset: (770164, 372)

Columns:
['id1', 'id2', 'id3', 'id4', 'id5', 'y', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68', 'f69', 'f70', 'f71', 'f72', 'f73', 'f74', 'f75', 'f76', 'f77', 'f78', 'f79', 'f80', 'f81', 'f82', 'f83', 'f84', 'f85', 'f86', 'f87', 'f88', 'f89', 'f90', 'f91', 'f92', 'f93', 'f94', 'f95', 'f96', 'f97', 'f98', 'f99', 'f100', 'f101', 'f102', 'f103', 'f104', 'f105', 'f106', 'f107', 'f108', 'f109', 'f110', 'f111', 'f112', 'f113', 'f114', 'f115', 'f116', 'f117', 'f118', 'f119', 'f120', 'f121', 'f122', 'f123', 'f124', 'f125', 'f126', 'f127', 'f128', 'f129', 'f130', 'f131', 'f132', 'f133', 'f134', 'f135', 'f136', 'f137', 'f138', 'f139', 'f140', 'f141', 'f142', 'f143', 'f144', 'f145', 'f146', 'f147', 'f148', 'f149', 'f150', 'f151', 'f152', 'f153', 'f154', 'f155', 'f156', 'f157', 'f158', 'f159', 'f160', 'f161', 'f162', 'f163', 'f164', 'f165', 'f166', 'f167', 'f168', 'f169', 'f170', 'f171', 'f172', 'f173', 'f174', 'f175', 'f176', 'f177', 'f178', 'f179', 'f180', 'f181', 'f182', 'f183', 'f184', 'f185', 'f186', 'f187', 'f188', 'f189', 'f190', 'f191', 'f192', 'f193', 'f194', 'f195', 'f196', 'f197', 'f198', 'f199', 'f200', 'f201', 'f202', 'f203', 'f204', 'f205', 'f206', 'f207', 'f208', 'f209', 'f210', 'f211', 'f212', 'f213', 'f214', 'f215', 'f216', 'f217', 'f218', 'f219', 'f220', 'f221', 'f222', 'f223', 'f224', 'f225', 'f226', 'f227', 'f228', 'f229', 'f230', 'f231', 'f232', 'f233', 'f234', 'f235', 'f236', 'f237', 'f238', 'f239', 'f240', 'f241', 'f242', 'f243', 'f244', 'f245', 'f246', 'f247', 'f248', 'f249', 'f250', 'f251', 'f252', 'f253', 'f254', 'f255', 'f256', 'f257', 'f258', 'f259', 'f260', 'f261', 'f262', 'f263', 'f264', 'f265', 'f266', 'f267', 'f268', 'f269', 'f270', 'f271', 'f272', 'f273', 'f274', 'f275', 'f276', 'f277', 'f278', 'f279', 'f280', 'f281', 'f282', 'f283', 'f284', 'f285', 'f286', 'f287', 'f288', 'f289', 'f290', 'f291', 'f292', 'f293', 'f294', 'f295', 'f296', 'f297', 'f298', 'f299', 'f300', 'f301', 'f302', 'f303', 'f304', 'f305', 'f306', 'f307', 'f308', 'f309', 'f310', 'f311', 'f312', 'f313', 'f314', 'f315', 'f316', 'f317', 'f318', 'f319', 'f320', 'f321', 'f322', 'f323', 'f324', 'f325', 'f326', 'f327', 'f328', 'f329', 'f330', 'f331', 'f332', 'f333', 'f334', 'f335', 'f336', 'f337', 'f338', 'f339', 'f340', 'f341', 'f342', 'f343', 'f344', 'f345', 'f346', 'f347', 'f348', 'f349', 'f350', 'f351', 'f352', 'f353', 'f354', 'f355', 'f356', 'f357', 'f358', 'f359', 'f360', 'f361', 'f362', 'f363', 'f364', 'f365', 'f366']

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id1,id2,id3,id4,id5,y,f1,f2,f3,f4,...,f357,f358,f359,f360,f361,f362,f363,f364,f365,f366
0,1366776_189706075_16-23_2023-11-02 22:22:00.042,1366776,189706075,2023-11-02 22:22:00.042,2023-11-02,0,1.0,NaN,NaN,NaN,...,NaN,-9999.0,0.0,NaN,28.0,0.0,0.00000,337.0,0.0,0.00000
1,1366776_89227_16-23_2023-11-01 23:51:24.999,1366776,89227,2023-11-01 23:51:24.999,2023-11-01,0,1.0,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,87.0,0.0,0.00000,1010.0,2.0,0.00198
2,1366776_35046_16-23_2023-11-01 00:30:59.797,1366776,35046,2023-11-01 00:30:59.797,2023-11-01,0,1.0,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,23.0,0.0,0.00000,1010.0,2.0,0.00198
3,1366776_6275451_16-23_2023-11-02 22:21:32.261,1366776,6275451,2023-11-02 22:21:32.261,2023-11-02,0,1.0,NaN,NaN,NaN,...,NaN,-9999.0,0.0,NaN,277.0,1.0,0.00361,337.0,0.0,0.00000
4,1366776_78053_16-23_2023-11-02 22:21:34.799,1366776,78053,2023-11-02 22:21:34.799,2023-11-02,0,1.0,NaN,NaN,NaN,...,NaN,-9999.0,0.0,NaN,359.0,0.0,0.00000,337.0,0.0,0.00000

In [5]:

df['y'].value_counts(normalize=True) * 100

y
0    95.189206
1     4.810794
Name: proportion, dtype: float64

In [6]:
import pandas as pd

# 📂 Paths to datasets
train_path = "/kaggle/working/train_data.csv"
events_path = "/kaggle/input/amex-dataset/add_event.parquet"
transactions_path = "/kaggle/working/transacrtion_data.csv"
offers_path = "/kaggle/input/amex-dataset/offer_metadata.parquet"

# 📥 Load datasets
train_df = pd.read_csv(train_path)
events_df = pd.read_parquet(events_path)
transactions_df = pd.read_csv(transactions_path)
offers_df = pd.read_parquet(offers_path)

# 🛠️ Fix mismatched dtypes for merge keys (convert to string)
merge_keys = ["id2", "id3"]  # Add other IDs if needed

for key in merge_keys:
    if key in train_df.columns:
        train_df[key] = train_df[key].astype(str)
    if key in events_df.columns:
        events_df[key] = events_df[key].astype(str)
    if key in offers_df.columns:
        offers_df[key] = offers_df[key].astype(str)
    if key in transactions_df.columns:
        transactions_df[key] = transactions_df[key].astype(str)

# 🔑 Merge Step 1: Merge train data with events
merged_df = train_df.merge(
    events_df,
    how="left",
    on=["id2", "id3"]
)

# 🔑 Merge Step 2: Merge with transactions
merged_df = merged_df.merge(
    transactions_df,
    how="left",
    on="id2"
)

# 🔑 Merge Step 3: Merge with offers metadata
merged_df = merged_df.merge(
    offers_df,
    how="left",
    on="id3"
)

# 📊 Inspect merged dataset
print(f"Merged dataset shape: {merged_df.shape}")
print("Sample columns:")
print(merged_df.columns.tolist())

# 📤 Save merged dataset (optional)
merged_df.to_csv("/kaggle/working/train_merged.csv", index=False)
print("✅ Merged dataset saved as train_merged.csv")

# Preview first few rows
merged_df.head()

Merged dataset shape: (770164, 394)
Sample columns:
['id1', 'id2', 'id3', 'id4_x', 'id5', 'y', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68', 'f69', 'f70', 'f71', 'f72', 'f73', 'f74', 'f75', 'f76', 'f77', 'f78', 'f79', 'f80', 'f81', 'f82', 'f83', 'f84', 'f85', 'f86', 'f87', 'f88', 'f89', 'f90', 'f91', 'f92', 'f93', 'f94', 'f95', 'f96', 'f97', 'f98', 'f99', 'f100', 'f101', 'f102', 'f103', 'f104', 'f105', 'f106', 'f107', 'f108', 'f109', 'f110', 'f111', 'f112', 'f113', 'f114', 'f115', 'f116', 'f117', 'f118', 'f119', 'f120', 'f121', 'f122', 'f123', 'f124', 'f125', 'f126', 'f127', 'f128', 'f129', 'f130', 'f131', 'f132', 'f133', 'f134', 'f135', 'f136', 'f137', 'f138', 'f139', 'f140', 'f141', 'f142', 'f143', 'f144', 'f145', 'f146', 'f147', 'f148', 'f149', 'f150', 'f151', 'f152', 'f153', 'f154', 'f155', 'f156', 'f157', 'f158', 'f159', 'f160', 'f161', 'f162', 'f163', 'f164', 'f165', 'f166', 'f167', 'f168', 'f169', 'f170', 'f171', 'f172', 'f173', 'f174', 'f175', 'f176', 'f177', 'f178', 'f179', 'f180', 'f181', 'f182', 'f183', 'f184', 'f185', 'f186', 'f187', 'f188', 'f189', 'f190', 'f191', 'f192', 'f193', 'f194', 'f195', 'f196', 'f197', 'f198', 'f199', 'f200', 'f201', 'f202', 'f203', 'f204', 'f205', 'f206', 'f207', 'f208', 'f209', 'f210', 'f211', 'f212', 'f213', 'f214', 'f215', 'f216', 'f217', 'f218', 'f219', 'f220', 'f221', 'f222', 'f223', 'f224', 'f225', 'f226', 'f227', 'f228', 'f229', 'f230', 'f231', 'f232', 'f233', 'f234', 'f235', 'f236', 'f237', 'f238', 'f239', 'f240', 'f241', 'f242', 'f243', 'f244', 'f245', 'f246', 'f247', 'f248', 'f249', 'f250', 'f251', 'f252', 'f253', 'f254', 'f255', 'f256', 'f257', 'f258', 'f259', 'f260', 'f261', 'f262', 'f263', 'f264', 'f265', 'f266', 'f267', 'f268', 'f269', 'f270', 'f271', 'f272', 'f273', 'f274', 'f275', 'f276', 'f277', 'f278', 'f279', 'f280', 'f281', 'f282', 'f283', 'f284', 'f285', 'f286', 'f287', 'f288', 'f289', 'f290', 'f291', 'f292', 'f293', 'f294', 'f295', 'f296', 'f297', 'f298', 'f299', 'f300', 'f301', 'f302', 'f303', 'f304', 'f305', 'f306', 'f307', 'f308', 'f309', 'f310', 'f311', 'f312', 'f313', 'f314', 'f315', 'f316', 'f317', 'f318', 'f319', 'f320', 'f321', 'f322', 'f323', 'f324', 'f325', 'f326', 'f327', 'f328', 'f329', 'f330', 'f331', 'f332', 'f333', 'f334', 'f335', 'f336', 'f337', 'f338', 'f339', 'f340', 'f341', 'f342', 'f343', 'f344', 'f345', 'f346', 'f347', 'f348', 'f349', 'f350', 'f351', 'f352', 'f353', 'f354', 'f355', 'f356', 'f357', 'f358', 'f359', 'f360', 'f361', 'f362', 'f363', 'f364', 'f365', 'f366', 'id6', 'id4_y', 'id7', 'f367', 'f368', 'f369', 'f370', 'f371', 'f372', 'id8_x', 'f374_x', 'id9', 'f375', 'f376', 'f377', 'id10', 'id11', 'f378', 'f374_y', 'id8_y', 'id12', 'id13']
✅ Merged dataset saved as train_merged.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id1,id2,id3,id4_x,id5,y,f1,f2,f3,f4,...,f375,f376,f377,id10,id11,f378,f374_y,id8_y,id12,id13
0,1366776_189706075_16-23_2023-11-02 22:22:00.042,1366776,189706075,2023-11-02 22:22:00.042,2023-11-02,0,1.0,NaN,NaN,NaN,...,2.0,2.0,None,1,None,g2baascbuyeectmpoanb1lo$bitscst,"Radio, Television, And Consumer Electronics St...",57310000,2023-11-01 00:00:00,2023-11-30 23:59:59
1,1366776_89227_16-23_2023-11-01 23:51:24.999,1366776,89227,2023-11-01 23:51:24.999,2023-11-01,0,1.0,NaN,NaN,NaN,...,2.0,NaN,None,1,None,ga$scbuyeectsamo$ioompoawb4lo1sc(o$st,Liquor Stores,59210000,2023-11-01 00:00:00,2024-04-30 23:59:59
2,1366776_35046_16-23_2023-11-01 00:30:59.797,1366776,35046,2023-11-01 00:30:59.797,2023-11-01,0,1.0,NaN,NaN,NaN,...,2.0,10.0,None,1,None,g1baascbuyeectmpoatb1lo$bitscst,Beauty Shops,72310000,2023-11-01 00:00:00,2023-11-30 23:59:59
3,1366776_6275451_16-23_2023-11-02 22:21:32.261,1366776,6275451,2023-11-02 22:21:32.261,2023-11-02,0,1.0,NaN,NaN,NaN,...,2.0,10.0,None,1,None,g1baascbuyeectmpoadb1lo$bitscst,Family Clothing Stores,56510500,2023-11-01 00:00:00,2023-11-30 23:59:59
4,1366776_78053_16-23_2023-11-02 22:21:34.799,1366776,78053,2023-11-02 22:21:34.799,2023-11-02,0,1.0,NaN,NaN,NaN,...,2.0,8.0,None,1,None,g8baascbuyeectmpoaeb1lo$bitscst,"Miscellaneous Retail Stores, Nec",59991300,2023-11-01 00:00:00,2023-11-30 23:59:59

In [7]:
merged_df.tail(50)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id1,id2,id3,id4_x,id5,y,f1,f2,f3,f4,...,f375,f376,f377,id10,id11,f378,f374_y,id8_y,id12,id13
770114,1858754_313795_16-23_2023-11-03 15:29:17.840,1858754,313795,2023-11-03 15:29:17.840,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gaocbuyeectsamo$ioomporrarcwypfyspc&ahpf1act,Hotels & Motels,70110803,2023-10-06 00:00:00,2023-12-31 23:59:59
770115,1858754_69479_16-23_2023-11-03 13:37:51.867,1858754,69479,2023-11-03 13:37:51.867,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,2,None,gao$scbuyeectsamo$ioompiamacooamb1st,Women's Accessory And Specialty Stores,56320000,2023-09-27 00:00:00,2023-12-27 23:59:59
770116,1858754_57941_16-23_2023-11-03 15:29:06.730,1858754,57941,2023-11-03 15:29:06.730,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,NaN,None,2,None,ga$scbuyeectsamo$ioompoakb1lo2sc(o$st,Meat & Fish Markets,54219902,2023-10-02 00:00:00,2023-12-15 23:59:59
770117,1858754_6919527_16-23_2023-11-03 15:28:47.851,1858754,6919527,2023-11-03 15:28:47.851,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,3.0,None,1,None,g3baascbuyeectmpoa7b1lo$bitscst,Family Clothing Stores,56510500,2023-11-01 00:00:00,2023-11-30 23:59:59
770118,1858754_281783_16-23_2023-11-03 15:29:21.560,1858754,281783,2023-11-03 15:29:21.560,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoagb2st,"Candy, Nut & Confectionery Stores",54410000,2023-11-01 00:00:00,2024-02-28 23:59:59
770119,1858754_31794_16-23_2023-11-03 15:29:16.042,1858754,31794,2023-11-03 15:29:16.042,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,6.0,None,1,None,g6baascbuyeectmpoacb1lo$bitscst,Shoe Stores,56610000,2023-11-01 00:00:00,2023-11-30 23:59:59
770120,1858754_23311_16-23_2023-11-02 21:39:38.953,1858754,23311,2023-11-02 21:39:38.953,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompiacsooacb1st,Family Clothing Stores,56510000,2023-10-02 00:00:00,2023-12-31 23:59:59
770121,1858754_29494_16-23_2023-11-03 15:29:18.342,1858754,29494,2023-11-03 15:29:18.342,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompiacaooacb4st,Utility Trailer And Recreational Vehicle Rental,75190000,2023-10-19 00:00:00,2024-04-19 23:59:59
770122,1858754_60848_16-23_2023-11-03 13:31:09.043,1858754,60848,2023-11-03 13:31:09.043,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoamb1st,Shoe Stores,56610000,2023-09-07 00:00:00,2024-01-31 23:59:59
770123,1858754_82957_16-23_2023-11-03 13:37:39.157,1858754,82957,2023-11-03 13:37:39.157,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoatb1st,Miscellaneous Food Stores,54990000,2023-06-22 00:00:00,2023-12-22 23:59:59
770124,1858754_60448_16-23_2023-11-03 13:30:38.000786,1858754,60448,2023-11-03 13:30:38.000786,2023-11-03,1,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoabb3st,Direct Selling Establishments,59630000,2023-11-03 00:00:00,2024-03-31 23:59:59
770125,1858754_90250_16-23_2023-11-02 21:39:13.698,1858754,90250,2023-11-02 21:39:13.698,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoamb1st,Medical & Hospital Equipment,50470000,2023-08-11 00:00:00,2023-12-31 23:59:59
770126,1858754_65430_16-23_2023-11-03 13:30:23.727,1858754,65430,2023-11-03 13:30:23.727,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,NaN,None,1,None,ga$scbuyeeaectmaspo$omoaoatb1lo1sc(o$st,Florists,59929901,2023-11-01 00:00:00,2024-01-31 23:59:59
770127,1858754_434753_16-23_2023-11-03 15:29:35.699,1858754,434753,2023-11-03 15:29:35.699,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,NaN,None,2,None,ga$scbuyeectsamo$ioompoabb2lo5sc(o$st,Retail Bakeries,54610000,2023-10-02 00:00:00,2024-02-29 23:59:59
770128,1858754_87164_16-23_2023-11-03 13:35:48.091,1858754,87164,2023-11-03 13:35:48.091,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,NaN,None,1,None,ga$scbuyeectmaspo$omospmoamb1lo2sc(o$st,Computer And Computer Software Stores,57340000,2023-10-06 00:00:00,2023-12-02 23:59:59
770129,1858754_72577_16-23_2023-11-03 13:30:57.375,1858754,72577,2023-11-03 13:30:57.375,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoamb1st,Liquor Stores,59210000,2023-10-02 00:00:00,2023-12-31 23:59:59
770130,1858754_153757225_16-23_2023-11-03 13:37:42.956,1858754,153757225,2023-11-03 13:37:42.956,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,5.0,None,1,None,g5baascbuyeectmpoavb1lo$bitscst,Women's Accessory And Specialty Stores,56320300,2023-11-01 00:00:00,2023-11-30 23:59:59
770131,1858754_57342_16-23_2023-11-03 15:29:37.280,1858754,57342,2023-11-03 15:29:37.280,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompiaosooaob1st,Meat & Fish Markets,54219902,2023-08-11 00:00:00,2023-12-31 23:59:59
770132,1858754_7382323_16-23_2023-11-03 13:30:29.043,1858754,7382323,2023-11-03 13:30:29.043,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,2.0,None,1,None,g2baascbuyeectmpoarb1lo$bitscst,Furniture Stores,57120102,2023-11-01 00:00:00,2023-11-30 23:59:59
770133,1858754_938326_16-23_2023-11-03 13:37:36.153,1858754,938326,2023-11-03 13:37:36.153,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,5.0,None,1,None,g5baascbuyeectmpoaeb1lo$bitscst,Miscellaneous Apparel And Accessory Stores,56990313,2023-11-01 00:00:00,2023-11-30 23:59:59
770134,1858754_648628_16-23_2023-11-03 13:38:12.338,1858754,648628,2023-11-03 13:38:12.338,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioomporrarcwypfysaehahyf5t1b...,Hotels & Motels,70110803,2023-05-05 00:00:00,2023-11-05 23:59:59
770135,1858754_30073_16-23_2023-11-03 15:29:10.481,1858754,30073,2023-11-03 15:29:10.481,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectmaspo$omiasnbpcooasb1st,Furniture Stores,57120000,2023-06-08 00:00:00,2023-12-08 23:59:59
770136,1858754_3460461_16-23_2023-11-03 13:30:29.053,1858754,3460461,2023-11-03 13:30:29.053,2023-11-03,0,NaN,NaN,NaN,NaN,...,2.0,5.0,None,1,None,g5baascbuyeectmpoaab1lo$bitscst,Shoe Stores,56610000,2023-11-01 00:00:00,2023-11-30 23:59:59
770137,1858754_56461_16-23_2023-11-03 15:29:35.283,1858754,56461,2023-11-03 15:29:35.283,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$uioomporrarcwypfysaphpilaf1t...,Hotels & Motels,70110000,2023-11-02 00:00:00,2024-01-31 23:59:59
770138,1858754_545624_16-23_2023-11-02 21:39:02.214,1858754,545624,2023-11-02 21:39:02.214,2023-11-02,0,NaN,NaN,NaN,NaN,...,2.0,8.0,None,1,None,g8baascbuyeectmpoaob1lo$bitscst,Bottled & Canned Soft Drinks,20860104,2023-11-01 00:00:00,2023-11-30 23:59:59
770139,1858754_287793_16-23_2023-11-03 13:29:38.606,1858754,287793,2023-11-03 13:29:38.606,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioomporrarcapcrlvdpf8t1ef+hpst,Hotels & Motels,70110700,2023-08-15 00:00:00,2023-11-15 23:59:59
770140,1858754_77109_16-23_2023-11-03 13:37:56.279,1858754,77109,2023-11-03 13:37:56.279,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoa1b4st,"Miscellaneous Retail Stores, Nec",59990000,2023-10-03 00:00:00,2024-04-02 23:59:59
770141,1858754_7114_16-23_2023-11-03 13:34:49.413,1858754,7114,2023-11-03 13:34:49.413,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoamb1st,Liquor Stores,59210000,2023-10-30 00:00:00,2023-12-31 23:59:59
770142,1858754_93527_16-23_2023-11-03 15:29:25.890,1858754,93527,2023-11-03 15:29:25.890,2023-11-03,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoacb1st,Liquor Stores,59210000,2023-10-12 00:00:00,2024-01-03 23:59:59
770143,1868186_807513_16-23_2023-11-01 14:59:52.220,1868186,807513,2023-11-01 14:59:52.220,2023-11-01,0,49.0,49.0,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompiaccgb1st,Sporting Goods And Bicycle Shops,59410000,2023-11-01 00:00:00,2024-01-15 23:59:59
770144,1889036_430736_16-23_2023-11-03 08:35:58.602,1889036,430736,2023-11-03 08:35:58.602,2023-11-03,0,13.0,NaN,NaN,NaN,...,2.0,6.0,None,1,None,g6baascbuyeectmpoatb1lo$bitscst,Family Clothing Stores,56510500,2023-11-01 00:00:00,2023-11-30 23:59:59
770145,1889036_184034_16-23_2023-11-03 08:35:57.298,1889036,184034,2023-11-03 08:35:57.298,2023-11-03,0,13.0,NaN,NaN,NaN,...,2.0,NaN,None,1,None,ga$scbuyeectsamo$ioompoanb2lo2sc(o$st,Men's And Boys' Clothing And Accessory Stores,56110000,2023-08-22 00:00:00,2024-02-22 23:59:59
770146,1889036_78053_16-23_2023-11-03 08:35:58.508,1889036,78053,2023-11-03 08:35:58.508,2023-11-03,0,13.0,NaN,NaN,NaN,...,2.0,8.0,None,1,None,g8baascbuyeectmpoaeb1lo$bitscst,"Miscellaneous Retail Stores, Nec",59991300,2023-11-01 00:00:00,2023-11-30 23:59:59
770147,1890991_97193_16-23_2023-11-02 15:30:15.729,1890991,97193,2023-11-02 15:30:15.729,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectmaspo$omoagb1st,"Offices And Clinics Of Health Practitioners, Nec",80491200,2023-10-05 00:00:00,2024-01-31 23:59:59
770148,1890991_70360_16-23_2023-11-02 15:30:13.972,1890991,70360,2023-11-02 15:30:13.972,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,ga$scbuyeectmaspo$uomapmb1vut6toppm($spmaastlpr,Family Clothing Stores,56510500,2023-07-03 00:00:00,2023-12-31 23:59:59
770149,1890991_78053_16-23_2023-11-02 15:30:15.832,1890991,78053,2023-11-02 15:30:15.832,2023-11-02,0,NaN,NaN,NaN,NaN,...,2.0,8.0,None,1,None,g8baascbuyeectmpoaeb1lo$bitscst,"Miscellaneous Retail Stores, Nec",59991300,2023-11-01 00:00:00,2023-11-30 23:59:59
770150,1890991_399752_16-23_2023-11-02 15:30:15.721,1890991,399752,2023-11-02 15:30:15.721,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompiauooaub1st,Family Clothing Stores,56510500,2023-08-30 00:00:00,2023-12-31 23:59:59
770151,1895178_77575_16-23_2023-11-01 10:27:29.757,1895178,77575,2023-11-01 10:27:29.757,2023-11-01,0,25.0,NaN,NaN,NaN,...,1.0,NaN,None,2,None,gao$scbuyeectsamo$ioompoapb1st,"Newspapers: Publishing, Or Publishing And Prin...",27110000,2023-10-26 00:00:00,2023-12-26 23:59:59
770152,1895178_94461_16-23_2023-11-01 10:27:29.750,1895178,94461,2023-11-01 10:27:29.750,2023-11-01,0,25.0,NaN,NaN,NaN,...,2.0,NaN,None,1,None,ga$scbuyeectmaspo$omoabb1lo2sc(o$emapst,Eating Places,58120000,2023-10-16 00:00:00,2024-01-14 23:59:59
770153,1895178_69638_16-23_2023-11-01 10:27:29.801,1895178,69638,2023-11-01 10:27:29.801,2023-11-01,0,25.0,NaN,NaN,NaN,...,1.0,NaN,None,1,None,g2amrpobuyeectsamo$ioompoasb1st,Family Clothing Stores,56510500,2023-10-30 00:00:00,2024-01-28 23:59:59
770154,1895178_360183_16-23_2023-11-01 10:27:29.657,1895178,360183,2023-11-01 10:27:29.657,2023-11-01,0,25.0,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompiaaeooab1eost,Family Clothing Stores,56510000,2023-07-24 00:00:00,2023-12-31 23:59:59
770155,1895178_98283_16-23_2023-11-01 10:27:29.758,1895178,98283,2023-11-01 10:27:29.758,2023-11-01,0,25.0,NaN,NaN,NaN,...,1.0,NaN,None,2,None,gao$scbuyeectsamo$ioompoadb1st,"Miscellaneous Retail Stores, Nec",59991300,2023-10-16 00:00:00,2024-01-16 23:59:59
770156,1895178_566484_16-23_2023-11-01 10:27:29.740,1895178,566484,2023-11-01 10:27:29.740,2023-11-01,0,25.0,NaN,NaN,NaN,...,1.0,NaN,None,2,None,gao$scbuyeectsamo$ioompoadb1st,"Miscellaneous Retail Stores, Nec",59991100,2023-08-01 00:00:00,2023-11-01 23:59:59
770157,1896641_57888_16-23_2023-11-02 08:14:21.510,1896641,57888,2023-11-02 08:14:21.510,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,2,None,gao$scbuyeectsamo$ioompoaab1st,Electronic Parts & Equipment,50650000,2023-09-29 00:00:00,2023-12-29 23:59:59
770158,1896641_725107_16-23_2023-11-02 08:14:24.479,1896641,725107,2023-11-02 08:14:24.479,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompdwdalb1fmoituapmbiust,"Air Transportation, Scheduled",45120100,2023-10-16 00:00:00,2023-12-31 23:59:59
770159,1896641_87731_16-23_2023-11-02 08:14:21.524,1896641,87731,2023-11-02 08:14:21.524,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoatb1st,"Miscellaneous Retail Stores, Nec",59991311,2023-10-02 00:00:00,2023-12-31 23:59:59
770160,1896641_505604_16-23_2023-11-02 08:14:24.458,1896641,505604,2023-11-02 08:14:24.458,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioomporrarcwypfysalhsf9t3balst,Hotels & Motels,70110000,2023-09-01 00:00:00,2024-03-01 23:59:59
770161,1896641_25212_16-23_2023-11-02 08:14:25.748,1896641,25212,2023-11-02 08:14:25.748,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$uioomporr&rcaparcpitumcr&ef9...,Hotels & Motels,70110000,2023-09-01 00:00:00,2023-12-15 23:59:59
770162,1900765_95157_16-23_2023-11-02 06:08:25.900,1900765,95157,2023-11-02 06:08:25.900,2023-11-02,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompiabdooabb2st,Miscellaneous Homefurnishings Stores,57190000,2023-11-01 00:00:00,2024-02-29 23:59:59
770163,1901215_95807_16-23_2023-11-01 11:01:33.086,1901215,95807,2023-11-01 11:01:33.086,2023-11-01,0,NaN,NaN,NaN,NaN,...,1.0,NaN,None,1,None,gao$scbuyeectsamo$ioompoazb1st,"Offices And Clinics Of Health Practitioners, Nec",80491200,2023-09-20 00:00:00,2024-01-31 23:59:59

In [8]:
import pandas as pd

# 📂 Load merged dataset
merged_path = "/kaggle/working/train_merged.csv"
df = pd.read_csv(merged_path)

print(f"Initial shape: {df.shape}")

# 1️⃣ Drop IDs and timestamps
drop_cols = [col for col in df.columns if "id" in col.lower() or "timestamp" in col.lower()]
df_cleaned = df.drop(columns=drop_cols, errors="ignore")
print(f"Shape after dropping IDs/Timestamps: {df_cleaned.shape}")

# 2️⃣ Handle categorical columns
cat_cols = df_cleaned.select_dtypes(include="object").columns.tolist()
print(f"Categorical columns: {cat_cols}")

# Fill NaNs in categorical columns with 'Missing' and encode
for col in cat_cols:
    df_cleaned[col] = df_cleaned[col].fillna("Missing")
    df_cleaned[col] = df_cleaned[col].astype("category").cat.codes

# 3️⃣ Fill NaNs in numerical columns
num_cols = df_cleaned.select_dtypes(include=["float64", "int64"]).columns.tolist()
df_cleaned[num_cols] = df_cleaned[num_cols].fillna(df_cleaned[num_cols].median())

print(f"Shape after cleaning: {df_cleaned.shape}")

# 📤 Save cleaned dataset
df_cleaned.to_csv("/kaggle/working/train_cleaned.csv", index=False)
print("✅ Cleaned dataset saved as train_cleaned.csv")

# 📊 Preview
df_cleaned.head()

Initial shape: (770164, 394)
Shape after dropping IDs/Timestamps: (770164, 379)
Categorical columns: ['f42', 'f50', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f354', 'f378', 'f374_y']
Shape after cleaning: (770164, 379)
✅ Cleaned dataset saved as train_cleaned.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,y,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f369,f370,f371,f372,f374_x,f375,f376,f377,f378,f374_y
0,0,1.0,31.0,31.0,40.0,34.0,36.0,34.0,35.0,39.0,...,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,82,78
1,0,1.0,31.0,31.0,40.0,34.0,36.0,34.0,35.0,39.0,...,NaN,NaN,NaN,NaN,NaN,2.0,6.0,NaN,279,54
2,0,1.0,31.0,31.0,40.0,34.0,36.0,34.0,35.0,39.0,...,NaN,NaN,NaN,NaN,NaN,2.0,10.0,NaN,45,8
3,0,1.0,31.0,31.0,40.0,34.0,36.0,34.0,35.0,39.0,...,NaN,NaN,NaN,NaN,NaN,2.0,10.0,NaN,40,35
4,0,1.0,31.0,31.0,40.0,34.0,36.0,34.0,35.0,39.0,...,NaN,NaN,NaN,NaN,NaN,2.0,8.0,NaN,193,69

In [9]:
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split

# 📂 Load cleaned dataset
df = pd.read_csv("/kaggle/working/train_cleaned.csv")

# 🎯 Separate features and target
X = df.drop(columns=["y"])  # drop target column
y = df["y"]

# 🪄 Train/test split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# ⚡ Train LightGBM model
model = lgb.LGBMClassifier(random_state=42)
model.fit(X_train, y_train)

# 📊 Get feature importances
importances = pd.Series(model.feature_importances_, index=X.columns)

# 🥇 Sort and select top 50
top50_features = importances.sort_values(ascending=False).head(50)
print("✅ Top 50 Important Features:")
print(top50_features)

# 🎯 Filter dataset to keep only top 50 features
X_top50 = X[top50_features.index]

# 📤 Save top 50 features dataset
X_top50["y"] = y  # add target back for later
X_top50.to_csv("/kaggle/working/train_top50.csv", index=False)
print("📁 Saved: train_top50.csv")

[LightGBM] [Info] Number of positive: 29702, number of negative: 586429
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.872165 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 47657
[LightGBM] [Info] Number of data points in the train set: 616131, number of used features: 302
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.048207 -> initscore=-2.982837
[LightGBM] [Info] Start training from score -2.982837
✅ Top 50 Important Features:
f350    91
f366    81
f223    62
f204    54
f206    47
f38     47
f203    44
f363    43
f210    41
f207    39
f314    37
f132    35
f134    34
f125    33
f142    33
f22     31
f39     31
f358    29
f41     28
f68     27
f76     27
f137    26
f31     26
f149    26
f133    25
f130    25
f96     25
f173    24
f312    24
f127    24
f126    24
f28     24
f138    24
f77     23
f139    23
f99     23
f167    23
f219    23
f30     21
f9      21
f29     20
f214    20
f212    19
f186    19
f146    19
f172    19
f59     19
f85     19
f319    19
f95     19
dtype: int32

/tmp/ipykernel_13/3916024269.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_top50["y"] = y  # add target back for later

📁 Saved: train_top50.csv